Windows: Fix some build warnings/link issues
* Fix MSVC error C4334 (32-bit bit shift)
* Load User32.dll functions at runtime instead of linking directly
  against library (fixes unresovled symbol errors on DDK build)

Signed-off-by: Chris Dickens <christopher.a.dickens@gmail.com>