darwin: Fix compilation on macOS 10.9 and earlier
kUSBReEnumerateCaptureDeviceMask was introduced in the 10.10 SDK, so
compiling on 10.9 and earlier will fail with:

 os/darwin_usb.c: In function 'darwin_reenumerate_device':
 os/darwin_usb.c:1749:18: error: 'kUSBReEnumerateCaptureDeviceMask' undeclared (first use in this function); did you mean 'USBReEnumerateOptions'?
        options |= kUSBReEnumerateCaptureDeviceMask;
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   USBReEnumerateOptions
 os/darwin_usb.c:1749:18: note: each undeclared identifier is reported only once for each function it appears in

Downstream report: https://trac.macports.org/ticket/63668

Closes #1023